# name: fernando_test

# on: [workflow_dispatch]

# jobs:
#   fernando_test:
#     name: testing action
#     runs-on: ubuntu-latest

name: 'fernando_test'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: 'fernandomatsuosantos/actions_tests'
        #ref: 'main'

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run Python
      run: |
        python3 script.py
      shell: bash